flex:
    report_base: ENC[AES256_GCM,data:Nh4tdA==,iv:hQe1bY6cN0Csgo0poi/pL59aojuYDVoOtS5aWixpH3s=,tag:BSW5eOaouierIV+PgFHN5w==,type:str]
    token: ENC[AES256_GCM,data:az/LSqEY0OzEb1fh3p9jx6N/ebPBXdiw,iv:h+kFEcS3ORzCw5WhRsq+mghLt7xfkgFGRBjQitINIEM=,tag:imsCA2MYCcC1002LDu5V1Q==,type:str]
    query_id: ENC[AES256_GCM,data:7DVH3aAf,iv:5pE4I2q3REujmVPT8rbNMtLoYqrdPW9t8zsGckWj41M=,tag:YiaSjZeiQH7haX806I91zg==,type:int]
    query_interval_in_days: ENC[AES256_GCM,data:HA==,iv:KiqprPLZC+t4ZRDRb3WMkWEKnuM/vfGMnDc4tNrG4co=,tag:oXK4KZJ0Jz6AfOPnaH+WcQ==,type:int]
rdb:
    username: ENC[AES256_GCM,data:0Y72uiZW,iv:96MlkfZcSSjWEvg3A5pEdCTXh9jYi/+I12iHKRatxKA=,tag:M5bTT64zBl3HDwuCbyxNUw==,type:str]
    password: ENC[AES256_GCM,data:abDaE2UVsNE1MwmdJu5OLQ==,iv:JWXlcRVWMS3whHm3AnW1vk1M565HjGDx3eRIbvYrM5Q=,tag:Qb9aQfXu7J0mSwT8NPX94A==,type:str]
    database: ENC[AES256_GCM,data:qx1adA==,iv:TkoLiI/pS74npmELGHjV4KLlyUFlsSlR9JsZf7xZ8dE=,tag:rnAncxYFvrmeg694W0uuVA==,type:str]
    host: ENC[AES256_GCM,data:Qmmx90FFdVY=,iv:O4D3Bxifm+6otYbKhkobHX8bS7JgYMD2VAWCXL/jVsA=,tag:8UgSvxyiKut20Z8xOMlCEw==,type:str]
    port: ENC[AES256_GCM,data:SDtHUg==,iv:LmWYvjmrn1wRUvrGrzQ+jK8NF6po8+kvpDwW0dIwW7E=,tag:Lx4DTDo084U4M0/cf2V15w==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w2vhmzzmjvp92mkywx8wk4ux9587pnvrx3d9lk3h5g8266anhykqmlg6qd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYejg4RmdkdnZUcWFRckEy
            QS9WcHEzWDQ1cFBGYnlybG00OENRbXZYb2dvClZzOHBFOUR6aUtWWitUUWVtbWxx
            TG91Rm5nakFENGhxL21yZXZIOEM4dDgKLS0tIFVyb05Fc0YxNmMxaVdFUG1BMFpw
            OFE1N2Z5eUh4eWRxR0xnTVgvUmN6dXMK9kvb0QGRfVwZdFVjxatBpnu76fES5BTp
            XIyf5uwrLOYsFe3j7jvtpVZecIOonTXHHhPvQo6u1IxcxygTArh3WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-09T07:32:25Z"
    mac: ENC[AES256_GCM,data:z7WUEf4CDgnppj/soFsxvFEXd3+45FwXNFQUPYvGr5JRzFQyc5zEZAS0VUn3tIZscriU2ROgjxU6dS1qpANxmQVlu+G7c4NboPKo6vkFHSz++eL6zibb3Fp9MlyXlVVf7KPLw/AhgAfyvB2aFVESKJw13Hrb4D9A1h+5qk7oPJo=,iv:n9XbW0tJDE+jjoaHC7hd9slaH7+Ix+TtI5FwCbKu/GA=,tag:Ou+cz/djWzDZQb35Sw7uvg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
